apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: catalogue-db-runner
spec:
  serviceAccountName: awraad-docker
  taskRef:
    name: catalogue-db
  params:
  - name: IMAGE
    value: "awraad/catalogue-db"
  resources:
    inputs:
    - name: project-level3
      resourceRef:
        name: catalogue-db-src

