apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: orders-runner
  namespace: test
spec:
  serviceAccountName: orders-docker
  taskRef:
    name: orders
  params:
  - name: IMAGE
    value: "awraad/orders"
  resources:
    inputs:
    - name: project-level3
      resourceRef:
        name: project-level3

