apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: orders-deploy
spec:
  resources:
    inputs:
    - name: project-level3
      type: git
  params:
  - name: pathToYamlFile
    description: The path to the yaml file to deploy within the git source
  - name: imageUrl
    description: Url of image repository
  - name: imageTag
    description: Tag of the images to be used.
  steps:
  - name: update-yaml
    image: alpine
    command: ["sed"]
    args:
      - "-i"
      - "-e"
      - "s;__IMAGE__;$(inputs.params.imageUrl):$(inputs.params.imageTag);g"
      - "/workspace/$(inputs.params.pathToYamlFile)"
  - name: run-kubectl
    image: lachlanevenson/k8s-kubectl
    command: ["kubectl"]
    args:
      - "apply"
      - "-f"
      - "/workspace/$(inputs.params.pathToYamlFile)"
