---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: test
  labels:
    name: payment
    namespace: test
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    name: payment
