piVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-prod-task
spec:
  resources:
    inputs:
    - name: project-level3
      type: git
  params:
  - name: pathToYamlFile
    description: The path to the yaml file to deploy within the git source
  steps:
  - name: run-kubectl
    image: lachlanevenson/k8s-kubectl
    command: ["kubectl"]
    args:
      - "apply"
      - "-f"
      - "/workspace/$(inputs.params.pathToYamlFile)"
      - "-n"
      - "prod"
