secret:
	kubectl create -f secret.yaml
payment:
	kubectl create -f /payment/resource.yaml
	kubectl create -f /payment/sa.yaml
	kubectl create -f /payment/task.yaml
	kubectl create -f /payment/runner.yaml
