apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: front-end-runner
  namespace: test
spec:
  serviceAccountName: front-end-docker
  taskRef:
    name: font-end
  params:
  - name: IMAGE
    value: "awraad/front-end"
  resources:
    inputs:
    - name: project-level3
      resourceRef:
        name: project-level3

