apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: front-end-runner
  namespace: test
spec:
  serviceAccountName: front-end-docker
  taskRef:
    name: front-end
  params:
  - name: IMAGE
    value: "awraad/front-end"
  resources:
    inputs:
    - name: front-end-resource
      resourceRef:
        name: front-end-resource

