apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: user-db-runner
spec:
  serviceAccountName: awraad-docker
  taskRef:
    name: user-db
  params:
  - name: IMAGE
    value: "awraad/user-db"
  resources:
    inputs:
    - name: project-level3
      resourceRef:
        name: user-db-src

