apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: catalogue-runner
spec:
  serviceAccountName: awraad-docker
  taskRef:
    name: catalogue
  params:
  - name: IMAGE
    value: "awraad/catalogue"
  resources:
    inputs:
    - name: project-level3
      resourceRef:
        name: catalogue-src

