apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: payment-runner
spec:
  serviceAccountName: awraad-docker
  taskRef:
    name: payment
  params:
  - name: IMAGE
    value: "awraad/payment"
  resources:
    inputs:
    - name: project-level3
      resourceRef:
        name: git-source
