apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: user-runner
  namespace: test
spec:
  serviceAccountName: awraad-docker
  taskRef:
    name: user
  params:
  - name: IMAGE
    value: "awraad/user"
  resources:
    inputs:
    - name: project-level3
      resourceRef:
        name: user-src

